issue-3-swipe-right
alicejeeunlee/final-project pull request #17
Opened 2022-09-20 22:01 UTC by alicejeeunlee

2022-09-20 22:10 UTC, thebearingedge requested changes

2022-09-20 22:10 UTC, thebearingedge commented on client/pages/discover.jsx
> +          getDoggo={this.getDoggo}/>
You can remove this `getDoggo` prop.

2022-09-20 22:10 UTC, thebearingedge commented on server/index.js
> +            }
Let's return this array instead of responding for more consistency.

```js
} else {
  return [doggo, org];
}
```

2022-09-20 22:10 UTC, thebearingedge commented on server/index.js
> +    .catch(err => next(err));
Let's respond here so it's a bit easier to tell what's going on.

```js
discoverDoggo()
  .then(results => res.json(results))
  .catch(err => next(err));
```

2022-09-21 21:56 UTC, alicejeeunlee commented
https://user-images.githubusercontent.com/106103291/191617549-eb3fd1a3-68fa-429d-881f-8ea323b8f0db.mp4

2022-09-21 22:01 UTC, thebearingedge approved these changes

2022-09-21 22:27 UTC, merged